---
#YAML header
title: "My analysis scripts"
author: "By Erin Caughey"
date:  "Last updated: `r Sys.Date()`"
output:
  html_document: 
    toc: true  #This establishes a table of contents
    to_depth: 1  #this indicates there will be just 1 layer
    toc_float: true  #TOC will float as you scroll down
    theme: flatly  #theme for page, http://www.datadreaming.org/post/r-markdown-theme-gallery/
---
### Libraries

```{r setup, include=FALSE, warning=FALSE, message=FALSE}

knitr::opts_chunk$set(echo = TRUE)
#this chunk of code comes automatically when you create a new markdown page
#it's needed for converting this page to HTML

#Load the libraries
library(tidyverse) #https://www.tidyverse.org/
library(dplyr) #Used for cleaning data
library(tidyr)
library(stringr)
library(janitor) #Used for cleaning data
library(rmarkdown) #used for building the HTML page
library(knitr) #used for building the HTML page
library(htmltools)
library(scales)
library(lubridate)
library(gghighlight)
```


# Themeing (taken from MVP graphic)

```{r graphic theme, message=FALSE}
test_theme <- function(){
  list(
      theme_minimal(),
      scale_fill_manual(values=c("#AA1E23", "#F03C4B", "#FB8987", "#FAC8C8"), 
                       name="Leagues",
                       breaks=c("MLB", "NBA", "NFL", "NHL"),
                       labels=c("MLB", "NBA", "NFL", "NHL"))
    )
}
```


# Filtering rows
Example from Descartes Lab mobility ranking during COVID shutdowns
```{r}
# Raw dataset
DL_mobility <- read_csv("../test-data/DL-us-mobility-daterow.csv")

# filter for string in column
DL_wisconsin_mob <-DL_mobility %>% filter(admin1 == "Wisconsin")

# Remove string from column (Removes the word "County" from "Milwaukee County" in column)
DL_wisconsin_mob_counties <- filter(DL_wisconsin_mob, admin_level == 2) %>% mutate(admin2 = str_remove_all(admin2, " County"))

# filter a group of values at once 
# Looks for values *%in%* `midwest` and filters those from `admin1`
# midwest - according to census region definition
midwest_states <- c("Iowa", "Kansas", "Minnesota", "Missouri", "Nebraska", "North Dakota", "South Dakota", "Indiana", "Illinois", "Michigan", "Ohio", "Wisconsin")
DL_midwest_mob <- DL_mobility %>% filter(admin1 %in% midwest_states, admin_level == 1)

#Filter for a specific time span using lubridate
#counties during April election week
DL_elections <- DL_wisconsin_mob_counties %>% filter(date >= as.Date("2020-04-01") & date <= as.Date("2020-04-14"))
```

